### ISSUE TITLE
Marked as malware by anti malware (false positive)

### ISSUE THREAD

**Issue by Dantasstic** [ElPumpo/TinyNvidiaUpdateChecker#131] opened 2022-11-27 08:56 UTC
As per the title, the latest update is being flagged by Window Defender as a severe trojan. The previous version (1.15.1) was not flagged, and no previous version has either. 

You may want to look into this and change whatever you did that made it start to flag on this version only.

Win32/Bearfoos.B!ml

![2022-11-27 - 0153-08](https://user-images.githubusercontent.com/48727187/204126878-2803f0f9-c0b7-4b96-8461-87d7e4b397b6.png)

**Comment by ElPumpo** [comment] 2022-11-27 17:07
Yea each freaking update keeps having false positives #124 it started happening after I added an extension that made so I don't have to also ship dll files. They are inside the executable instead.

**Comment by Dantasstic** [comment] 2022-11-28 02:49
Interesting, I went back to 1.15.1 because it was _not_ being false detected. I wonder why some people get detections on certain versions but others don't. I also never got a detection on 1.15.0 as listed in that posted.

**Comment by ElPumpo** [comment] 2022-11-29 09:21
No both 1.15.1 and 1.15.0 were also false positives

**Comment by Dantasstic** [comment] 2022-11-30 01:51
> No both 1.15.1 and 1.15.0 were also false positives

Strange, they aren't flagged on my system. I just re-scanned them both specifically and Defender didn't make a peep.

**Comment by ElPumpo** [comment] 2022-11-30 08:05
Well they were on release

**Comment by DMT4all** [comment] 2022-11-30 09:23
> > No both 1.15.1 and 1.15.0 were also false positives
> 
> Strange, they aren't flagged on my system. I just re-scanned them both specifically and Defender didn't make a peep.

same here. only latest update gets detected

**Comment by Dantasstic** [comment] 2022-12-16 14:20
Same issue with 1.15.3

**Comment by Technetium1** [comment] 2022-12-16 17:00
> Well would that help that defender keeps flagging it positive?

@ElPumpo Probably not, BUT it would hopefully stop people from opening issues about false positives when they can click to see the scan results. Maybe consider using their `Monitor` service that's intended to catch false positives early: https://developers.virustotal.com/reference/monitor

**Comment by ElPumpo** [comment] 2022-12-21 18:11
Interesting. I will take a look into this and implement some auto upload thing

**Comment by ElPumpo** [comment] 2022-12-31 18:16
Possibly fixed with new .NET single file thing.

**Comment by ElPumpo** [comment] 2023-01-03 22:21
Hi and happy new years. I have migrated from .NET Framework to .NET now which has a "Produce single file" feature. I am just guessing that it will solve the false positives that Costura.Fody previously introduced.

[TinyNvidiaUpdateChecker 1.15.5 beta 1.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/10340146/TinyNvidiaUpdateChecker.1.15.5.beta.1.zip)

Please try this new version out I am thankful for the feedback

**Comment by Dantasstic** [comment] 2023-01-05 05:40
> Hi and happy new years. I have migrated from .NET Framework to .NET now which has a "Produce single file" feature. I am just guessing that it will solve the false positives that Costura.Fody previously introduced.
> 
> [TinyNvidiaUpdateChecker 1.15.5 beta 1.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/10340146/TinyNvidiaUpdateChecker.1.15.5.beta.1.zip)
> 
> Please try this new version out I am thankful for the feedback

Hmm, it just flashes momentarily on the screen and then is gone for me.

**Comment by Dantasstic** [comment] 2023-01-05 09:44
Can you please provide instructions?

**Comment by ElPumpo** [comment] 2023-01-05 10:05
Yes but did you install both x86 and amd64 Runtime?

**Comment by ElPumpo** [comment] 2023-01-05 11:56
No dont install the SDK just the runtime I belive haha. I will probably publish framework independent..

Yes install both x64 and x86. The tool is built for x86 but you prob need both

**Comment by Dantasstic** [comment] 2023-01-05 13:03
> No dont install the SDK just the runtime I belive haha.

I tried that, but it still doesn't run. Like I said, it then mentions a missing framework.

**Comment by ElPumpo** [comment] 2023-01-05 13:23
Okay yea I messed up there. Will release a new beta that is framework independent. But no false positives right?

**Comment by Dantasstic** [comment] 2023-01-05 13:24
No, no false positives! :)

**Comment by ElPumpo** [comment] 2023-01-05 13:38
Good!

**Comment by Dantasstic** [comment] 2023-01-05 13:49
I got it to run by installing the full SDK, which includes 3 runtimes (**.NET Runtime 7.0.1**, **ASP.NET Core Runtime 7.0.1** and **.NET Desktop Runtime 7.0.1**), although the one it seemed to actually want was the ASP.NET Core and not the .NET Runtime.

I just installed only **.NET SDK x86 version 7.0.1**, so no need for the x64 currently.

**Comment by ElPumpo** [comment] 2023-01-05 14:31
🙏😂 good. I will see about releasing framework independent. Good thing this beta was shared so this wouldnt appear later

**Comment by ElPumpo** [comment] 2023-01-05 15:40
Good but I belive this issue now can be closed as it no longer is an issue.

**Comment by ElPumpo** [comment] 2023-01-26 21:16
Still an issue...

**Comment by Virond** [comment] 2023-02-01 13:48
This is now being flagged for v1.16.3 too.

**Comment by ElPumpo** [comment] 2023-02-01 14:10
Can you show me

**Comment by Technetium1** [comment] 2023-02-01 21:09
@ElPumpo maybe some of this will be clues to why the false positive triggers: https://www.hybrid-analysis.com/sample/9024318d65a28d5c244a4022ae3e16bbde26eb762ba14942021d27f15f7f49eb/63dab89d34fe65742f11fbfd

**Comment by ElPumpo** [comment] 2023-02-02 09:06
![Screenshot_20230202-100519](https://user-images.githubusercontent.com/12564301/216279494-a4d551de-206e-4ab3-bf7b-3c7e38a7bd89.png)

Hold your phones does the credits in TNUC source code trigger this bullshit? It's commented code!

**Comment by ElPumpo** [comment] 2023-02-02 09:11
![Screenshot_20230202-101030](https://user-images.githubusercontent.com/12564301/216280850-56ba8f1b-3860-4531-961d-7e40ffcb69bb.png)

Thanks for the website I did not know it existed! So my commented code With the credits for the github gists is the cause of all of this?!

Lol

**Comment by Technetium1** [comment] 2023-02-02 09:57
Well if that's really the cause here, we can blame a bad YARA rule, and that would be a really stupid thing to trigger it. There are lots of sites for malware analysis, but not many free ones, especially that tell you exactly which rulesets trigger, instead of just a heuristic signature. H-A is one of the better ones in my opinion. Any.run is a good competitor, but only really decent to get a quick look at what malware is dropping and contacting, unless you pay.

**Comment by ElPumpo** [comment] 2023-02-02 11:24
Okay cool. I sent a new version I built without that gist url for analysis I'll post the results when they are in

**Comment by ElPumpo** [comment] 2023-02-02 18:16
![image](https://user-images.githubusercontent.com/12564301/216407957-7a8412db-f45b-4f6f-a0f2-dc27a11e5eab.png)
![image](https://user-images.githubusercontent.com/12564301/216408026-ffed001f-5b67-472c-8c96-e22c43eada73.png)

accually its the nvidia-data metadata URL being flagged. But I can replace the URL with

- `https://github.com/ZenitH-AT/nvidia-data/raw/main/gpu-data.json` for example instead of `raw.githubusercontent.com`

I have now built and uploaded for analysis. Let's wait and see the results. Because I belive this issue came when I added the metadata repo..

https://www.hybrid-analysis.com/sample/ea7c91946c6886f785fe7938071fbda0db3f001bad2d74233a12415464e974d4

**Comment by Technetium1** [comment] 2023-02-02 21:55
It's still showing some false positives, but it's gone from 20% detection rate to 7%, wonderful!

**Comment by ElPumpo** [comment] 2023-02-02 22:16
Yes the MetaDefender still is at 7%. I have contacted both Bitdefender and Emsisoft about this to resolve the false positive.

**Comment by 33b5e5** [comment] 2023-02-03 00:06
Defender just flagged 1.16.4 for me. That's the first time any release has been flagged on this Win 11 machine, and I know I've installed versions 1.15.4, 1.16.1 and 1.16.3 without incident (and probably a few more, but those are the binaries I still have on hand).

<img width="688" alt="Screenshot 2023-02-02 160144" src="https://user-images.githubusercontent.com/2781306/216478765-bcd798be-57d9-48e8-9d28-3786472abad0.png">

**Comment by ElPumpo** [comment] 2023-02-19 15:53
The analysis for v1.16.4 is marked as clean "Anti virus results" by Hybrid Analysis

![image](https://user-images.githubusercontent.com/12564301/219959068-e0ad96b0-6c22-46c1-b15c-12785c9bc2cc.png)

But still Falcon sandbox reports reports 1 virus indicator..

![image](https://user-images.githubusercontent.com/12564301/219959175-29e856b4-ba34-4ff2-8e2a-cdb6439f8f50.png)

Which makes no sense at all!

**Comment by 33b5e5** [comment] 2023-02-22 20:30
I just tried downloading 1.16.4 again, via the prompt from 1.16.3, and this time it downloaded and installed without triggering Defender. 🎉

**Comment by Technetium1** [comment] 2023-02-22 20:50
@ElPumpo that is telling you that it's not triggering directly, but that other AV engines still flagged it. If it sees even false positives, it will warn on it, just in case.

**Comment by ElPumpo** [comment] 2023-02-22 22:03
Ah okay but totally obfuscated code is not marked as malware by these sites? So if I just obfuscate it all then silly problem solved

**Comment by Technetium1** [comment] 2023-02-23 02:05
Usually the obfuscation is picked up itself, and adds HUGE bulk to the program, but yeah that's the nature of hunting malware ._.

**Comment by ElPumpo** [comment] 2023-05-13 11:46
Let's see if v1.16.5 will have the same issue still...

**Comment by ElPumpo** [comment] 2023-08-20 09:38
Perhaps the simple thing that the file is not signed is causing all of this? But I belive signing exe costs money right?

**Comment by ElPumpo** [comment] 2024-05-04 08:34
Closing due to no activity

**Closed by ElPumpo** 2024-05-04 08:34 UTC
