### ISSUE TITLE
Minimal installer not working (397.93 setup.exe error)

### ISSUE THREAD

**Issue by joluke** [ElPumpo/TinyNvidiaUpdateChecker#41] opened 2018-05-24 23:47 UTC
There is an error when running the installer saying: The setup can't find the specified file

here are the nvidia logs of such issue:

      0.226 |    DEBUG: [NVI2.CEngineCache] 1918@CEngineCache::CacheManifestFiles : Flattening C:\Users\joaopsantos\Downloads\TinyNvidiaUpdateChecker\NVI2\progress.htm. 
      0.229 |     INFO: [NVI2.CEngineCache] 1935@CEngineCache::CacheManifestFiles : Copied C:\Users\joaopsantos\Downloads\TinyNvidiaUpdateChecker\NVI2\progress.htm to C:\Program Files\NVIDIA Corporation\Installer2\installer.{C4C21A18-E15D-40EA-A9C7-1D1D07D98ADE}\.\progress.htm. 
      0.235 |    ERROR: [NVI2.NVManifestFile] 54@CNVManifestFile::CopyOrCheck : Manifest file ".\GFExperience\EULA.html" missing source directory C:\Users\joaopsantos\Downloads\TinyNvidiaUpdateChecker\GFExperience. 
      0.235 |     INFO: [NVI2.CEngineCache] 1980@CEngineCache::CachePerManifest : Exiting Checkpoint: Caching "installer" ( 32 ms ).

**Comment by joluke** [comment] 2018-05-25 01:32
This issue is easily bypassed by not deleting the directory with the name: GFExperience
Not deleting it, will make the setup.exe behave normally. Found the fix on guru3d

**Comment by ElPumpo** [comment] 2018-05-25 04:10
Duplicate of #40 but whatever. GDPR broke this application, just awesome!. Seems like `GFExperience\EULA.html` must exist now.

**Comment by cywq** [comment] 2018-05-25 07:18
Where do i find that EULA.html. I searched the whole web but cant find it.

**Comment by mt025** [comment] 2018-05-25 10:02
After adding the following it worked:
`GFExperience\EULA.html`
`GFExperience\PrivacyPolicy\PrivacyPolicy_*.htm`
`GFExperience\FunctionalConsent*.txt`

**Comment by cywq** [comment] 2018-05-25 10:31
#42 should fix that

**Comment by OneSlize** [comment] 2018-05-26 03:04
Ah sorry man, i swear i read the other issues before posting but i completely missed this. Happy that others are seeing as well however.

**Comment by xeropresence** [comment] 2018-06-05 20:41
Adding the files mentioned in https://github.com/ElPumpo/TinyNvidiaUpdateChecker/issues/41#issuecomment-392005262
Will get the installer to start, but install will fail saying the package is corrupted. Trying to install  398.11

**Comment by joluke** [comment] 2018-06-05 20:43
Deleting these lines in setup.cfg fixes such error:

<file name="${{EulaHtmlFile}}"/>
<file name="${{FunctionalConsentFile}}"/>
<file name="${{PrivacyPolicyFile}}"/>

Source: guru3d

**Comment by xeropresence** [comment] 2018-06-05 20:51
I was about to post the same thing. I found the thread and did a clean extract, removed those lines and now its installing.

**Comment by cywq** [comment] 2018-06-05 21:53
#46 should finally fix it if @ElPumpo is fine with my approach

**Comment by OdinGitDat** [comment] 2018-06-05 23:05
When is the fix for this going to be pushed for release?

**Comment by OneSlize** [comment] 2018-06-05 23:18
@mt025 Could you elaborate on how to properly do what you said, i tried but it still fails.

**Comment by mt025** [comment] 2018-06-05 23:27
@OneSlize Sure :-

1. Select Download and extract from the update checker
2.  Opened `398.11-desktop-win10-64bit-international-whql.exe` with 7zip and went into the `GFExperience` folder
3. Created a new folder called `GFExperience` in selected folder for extraction
4. Extracted EULA.html to the `GFExperience` folder
5. Extracted all FunctionalConsent*.txt files to the `GFExperience` folder
6. Extracted PrivacyPolicy Folder `GFExperience` folder
7. Ran setup.exe

Just did an update now, and its still working.

**Comment by ElPumpo** [comment] 2018-06-06 09:21
Fix in progress thanks to @cywq

**Closed** 2018-06-06 09:38 UTC
Labels: bug, priority

**Comment by ElPumpo** [comment] 2018-06-06 10:15
v1.13.0 released with fix, thanks everyone for the help!
