### ISSUE TITLE
v1.16.4 is automatically deleted by windows defender

### ISSUE THREAD

**Issue by keton** [ElPumpo/TinyNvidiaUpdateChecker#164] opened 2023-02-03 06:25 UTC
As in title. To repro just download from github and get 'Threats neutralized' popup. Previous versions worked. W11 with latest updates.

This is how it classifies TNUC:
![image](https://user-images.githubusercontent.com/2270836/216528349-2c8ce285-26b8-4b06-a156-611c851e379f.png)

And it does not want to release it from quarantine.

**Comment by ElPumpo** [comment] 2023-02-03 12:35
🧐 dupe of #131

**Closed by ElPumpo** 2023-02-03 12:35 UTC
