### ISSUE TITLE
Detected correct GPU (it seems) BUT incompatible driver with Supported Hardware

### ISSUE THREAD

**Issue by lucknaumann** [ElPumpo/TinyNvidiaUpdateChecker#71] opened 2019-12-30 10:21 UTC
**It** seems that my GPU was correctly identified but it wants to install an "upgraded version", which is an incompatible driver for my system.

Specs:
Windows 10 64bit
**GeForce 700M Series (Notebooks)** / **GeForce GTX 770M** [**_checked as being supported by this program_**]

The latest driver for my GPU according to [Nvidia](https://www.geforce.com/drivers):
**GeForce GTX 770M** [425.31](https://www.geforce.com/drivers/results/145874) (This driver will no longer be updated).

What this program _wants_ to install: 441.66
![TinyNvidiaUpdateChecker](https://user-images.githubusercontent.com/51302763/71576030-69715d00-2aac-11ea-968b-b218ec0a936c.PNG)

**Comment by ElPumpo** [comment] 2019-12-30 11:23
Dupe of #69

**Comment by lucknaumann** [comment] 2019-12-30 18:05
Hi, this actually isn't a dup as my hardware IS supported, unless something has changed. Thanks.

**Comment by lucknaumann** [comment] 2019-12-30 18:12
Actually, other than reporting a bug that you might want to look into, I've just discovered that [Chocolatey](https://chocolatey.org/packages/nvidia-display-driver/425.31) will install what I need. Thanks for this program, which worked well until that update, and good luck with it!

**Comment by ElPumpo** [comment] 2020-05-14 17:12
Accually what we need to implement is to properly get the IDs [here](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/620694e4db8b4cbf44fa2b8d4295a034a55c6f7c/TinyNvidiaUpdateChecker/MainConsole.cs#L552), then the application will always show the proper latest version available and not some hardcoded variable.

**Comment by ElPumpo** [comment] 2020-05-14 17:12
And you're wrong, this in fact is a duplication of #69

**Closed by ElPumpo** 2020-05-14 17:12 UTC
